#!/bin/bash
set -e

# Copy this hook to the .git/hooks directory to build
# the Jekyll site and publish it to gh-pages when
# attempting to push to master.

commit_msg="$1"
temp_dest=`mktemp -d`

echo "Building Jekyll site on $temp_dest"
jekyll build -d "$temp_dest" >/dev/null 2>&1

echo "Preparing to push to gh-pages"
git checkout gh-pages

echo "Empty current working tree..."
find . -not -wholename "*.git*" -delete

echo "Adding generated Jekyll content..."
rsync -a "$temp_dest"/ .
git add --all :./
git commit -m"$commit_msg"

git checkout -

exit 0
