#!/bin/bash

# Copy this hook to the .git/hooks directory to build
# the Jekyll site and publish it to gh-pages when
# attempting to push to master.

remote="$1"
url="$2"

while read local_ref local_sha remote_ref remote_sha
do
    temp_dest=`mktemp -d`
    build_msg="Building Jekyll site for $local_sha"

    echo "$build_msg on $temp_dest"
    bundle exec jekyll build -d "$temp_dest"

    echo "Preparing to push to gh-pages"
    git checkout gh-pages

    echo "Empty current working tree..."
    find . -not -wholename "*.git*" -delete

    echo "Adding generated Jekyll content..."
    rsync -a "$temp_dest"/ .
    git add --all :./
    git commit -m\""$build_msg"\"

    echo "Pushing to gh-pages..."
    git push --no-verify "$remote" "gh-pages"

    git checkout -
    git checkout .
done

exit 0
